### PR TITLE
Plugin Normalizer function: make filename lowercase

### PR DESCRIPTION
**Pull request by zzplab**
I prefer making de filename lowercase always. I propose a pull request to have it build in the master in that way, that the user can decide to turn the option on or off.
Default: off
I hope pull request is ok this way ;-)

### CODE REVIEW

**Comment by nao-pon** [comment]
@zzplab Thanks! :+1: 

"$path" will be assigned at the time holder uploads Chrome. It is the underlying holder name of the upload destination. If they are good even without lowercasing?

**Comment by zzplab** [comment]
Not that familiar with git yet :-) Thanks for the steps to change the pr.

Yes, I say $path is good without lowercasing (if I understand what you mean.)
If the path in the destination contains uppercase chars, that should not be changed, I suppose.
When uploading:
/home/MYUSER/www/files/NewFile.JPG
Should become:
/home/MYUSER/www/files/newfile.jpg
Just the filename that is uploaded or the dir name that is added.

**Comment by nao-pon** [comment]
Because I English is not good, it may to be confusing.

The target holder not included in `$path`.

**In case elFinder root is `/home/MYUSER/www/files`**
- Uploading `NewFile.JPG`
  - $path = '', $name = 'NewFile.JPG'
- Uploading `NewDir/NewFile.JPG` with chrome (Chrome is possible folder upload)
  - $path = 'NewDir', $name = 'NewFile.JPG'

**Comment by zzplab** [comment]
OK, I get it now. Clear. In that case $path should be lowercased as well.
Do I change that? Again new PR or ... ? ;-)

**Comment by nao-pon** [comment]
You may be committed to the elFinder branch of your repository.　:ok:

**Comment by zzplab** [comment]
I have already reset my elFinder branch...
I'll do that tomorrow.

**Comment by nao-pon** [comment]
Your elFinder's branch `elFinder` is alive. ( https://github.com/zzplab/elFinder/tree/elFinder ) and You can also be edited on GitHub. ( https://github.com/zzplab/elFinder/edit/elFinder/php/plugins/Normalizer/plugin.php )

**Comment by nao-pon** [comment]
Thanks! :+1:

**Pull request merged**
