### PR TITLE
Mounting Google Drive with elFinder

### PR DESCRIPTION
**Pull request by rajasharma27**
Mounting Google Drive in elFinder with google-api-php-client-2.0.0-RC7 or above

### CODE REVIEW

**Comment by nao-pon** [comment]
@rajasharma27 From where the First noticed...
Please omit the unnecessary things about the options. Also, please let versatility without defining a value. For example, such as callback or path.

**Comment by rajasharma27** [comment]
sir, I want user give only connector url in the redirecturi,
 if (isset($_GET['code'])) {
	$callback = new elFinderVolumeGoogleDrive();
	$callback->netmountPrepare(array());  //prepare callback url
    exit();
  }
when remove this from connector, drive class not read the value from define variable from connector class, because these variable define after this
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeGoogleDrive.class.php';

suggest me

**Comment by rajasharma27** [comment]
according to your code
// // AND reuire regist redirect url to "YOUR_CONNECTOR_URL?cmd=netmount&protocol=googledrive&host=1"

working without callback or path

**Comment by rajasharma27** [comment]
thanks

**Pull request closed without merging**
