### PR TITLE
Update bg translation

### PR DESCRIPTION
**Pull request by nmpetkov**
Added missing translations and some improvement to existing.

### CODE REVIEW

**Comment by nao-pon** [comment]
@nmpetkov Thanks! 👍

**Comment by nmpetkov** [comment]
@nao-pon Thank you for merging, but I cannot  see changes into destination file:
https://github.com/Studio-42/elFinder/blob/2.1/js/i18n/elfinder.bg.js
Many translations are missing, it seems it is the old one.

**Comment by nao-pon** [comment]
@nmpetkov Your PR was sent to 2.1 but I missed check it. so I done re-merged to master.

Thanks again! 👍

**Comment by nmpetkov** [comment]
Thank you.
What branch to use for sending PRs in future?

**Comment by nao-pon** [comment]
Please send to master branch.

**Pull request merged**
