### PR TITLE
Fix invalid grant bad request

### PR DESCRIPTION
**Pull request by migrad**
Hello @nao-pon,

Regardless of the problem with composer ( #3033 ), I have copied the dependencies of a previous version, and it works correctly.

However, when I try to connect to Google Drive it gives me "errReauthRequire". I have located that this error occurs because authentication failed with the "invalid_grant - Bad Request" error (id_client, secret_id and include autoload are good).

I have corrected it and get the token.

But the whole process stands still in this return (elFinderFlysystemGoogleDriveNetmount.php) :

```
            if (!empty($_GET['code']) && !$aToken) {
                $aToken = $client->fetchAccessTokenWithAuthCode($_GET['code']);
                $options['access_token'] = $aToken['access_token'];
                $this->session->set('GoogleDriveTokens', $aToken['access_token'])->set('GoogleDriveAuthParams', $options);
                $out = array(
                    'node' => $options['id'],
                    'json' => '{"protocol": "googledrive", "mode": "done", "reset": 1}',
                    'bind' => 'netmount'
                );
                return array('exit' => 'callback', 'out' => $out);
            }
```
Once the callback is executed, a page with a "Close this Window" is displayed and does nothing else.

I understand that at this point, the new window should close and reload elFinder to show the Google Drive driver, is that so?

I have also observed that the session data is deleted, when they should be maintained in order to perform that elFinder reload, right?.

I hope your help, thanks.

### CODE REVIEW

**Comment by nao-pon** [comment]
@migrad I tested of netomount via FlysystemGoogleDriveNetmount. And It was no problems.

Please try and check with the[ nightly build](https://github.com/Studio-42/elFinder/archive/2.1.zip).

**Comment by migrad** [comment]
I have downloaded it and installed the dependencies, but it gives me the following error (clean installation):

> {"exit":true,"error":"errReauthRequire"}

> /php/connector.minimal.php?cmd=netmount&protocol=googledrive&host=1&code=xxx&scope=https://www.googleapis.com/auth/drive

I have deleted the value of the code parameter, but I receive it correctly.

The constants ELFINDER_GOOGLEDRIVE_CLIENTID and ELFINDER_GOOGLEDRIVE_CLIENTSECRET have the correct values. Uncomment "require './vendor/autoload.php';" and "elFinder::$netDrivers['googledrive'] = 'FlysystemGoogleDriveNetmount';"

At this point I detected that this equality was always false:

> $options['user'] === 'init'

With what $aToken is always false.

**Comment by nao-pon** [comment]
@migrad What are your browsers using? Is the result the same when using a Chrome incognito window?

**Comment by nao-pon** [comment]
@migrad Make sure the `php/.tmp` directory exists and writable by PHP.

**Comment by nao-pon** [comment]
@migrad I close this because we can't reproduce the problem. You can submit a new PR at any time. Thank you!

**Pull request closed without merging**
