### PR TITLE
Create elfinder.in.js

### PR DESCRIPTION
**Pull request by lokothodida**
Indonesian language file created by @esyede in issue #1060. Not sure if this should go in 2.x, 2.1 or both.

### CODE REVIEW

**Comment by nao-pon** [comment]
@lokothodida , @esyede Thanks!

ISO_639-1 says "Indonesian" is "id". so I think "elfinder.id.js" is more better.

**Comment by lokothodida** [comment]
My bad. I'd looked at this [site](http://www.sitepoint.com/web-foundations/iso-2-letter-language-codes/) for the language codes, when most other places seem to say `id`.

**Comment by nao-pon** [comment]
Thanks!

**Comment by esyede** [comment]
'in' is for India :)
Thanks @nao-pon @lokothodida !

**Pull request merged**
