### PR TITLE
MSSql table structure for mounting in elFinder

### PR DESCRIPTION
**Pull request by rajasharma27**
MSSql table structure for mounting in elFinder

### CODE REVIEW

**Comment by nao-pon** [comment]
@rajasharma27 I do not know much about MsSql. Is this thing generic? (e.g. "DF__elfinder_f__mime__7F60ED59")

**Comment by rajasharma27** [comment]
actually 7F60ED59 this type of value I found somewhere, not clear use in constraints name

**Comment by nao-pon** [comment]
@rajasharma27 I don't know well about MsSql. Please make clearly. And, SQL query "ALTER TABLE" can be included in "CREATE TABLE"?

**Comment by nao-pon** [comment]
There is a regrettable, but we drop the MsSQL driver. Because it can not be maintained to continue because I am not familiar with MsSQL.

So you can listed in the README as a third-party volume driver, please PR to README.md.

**Pull request closed without merging**
