### PR TITLE
Custom auto rename when upload

### PR DESCRIPTION
**Pull request by huynhquocbao92**
Hi Admin,
I need custom function **sanitizeFileName** when upload file for my project because use **Plugin.Sanitizer.onUpLoadPreSave** config replace character can't resolve my problem.
Please helpe me accept this pull request.
Thanks you very much.

### CODE REVIEW

**Comment by nao-pon** [comment]
@huynhquocbao92 I can not accept your pull request to the Sanitizer plugin, but since I changed the sanitizeFileName function from private to protected, you can customize it with the extended class.

e.g.
- plugins
    - MySanitizer
        - plugin.php
```php
<?php
/*
 * ex. binding, configure on connector options
 *	$opts = array(
 *		'bind' => array(
 *			'upload.pre mkdir.pre mkfile.pre rename.pre archive.pre ls.pre' => array(
 *				'Plugin.MySanitizer.cmdPreprocess'
 *			),
 *			'ls' => array(
 *				'Plugin.MySanitizer.cmdPostprocess'
 *			),
 *			'upload.presave' => array(
 *				'Plugin.MySanitizer.onUpLoadPreSave'
 *			)
 *		),
 *		// global configure (optional)
 *		'plugin' => array(
 *			'MySanitizer' => array(
 *				'enable' => true,
 *			)
 *		),
 *		// each volume configure (optional)
 *		'roots' => array(
 *			array(
 *				'driver' => 'LocalFileSystem',
 *				'path'   => '/path/to/files/',
 *				'URL'    => 'http://localhost/to/files/'
 *				'plugin' => array(
 *					'MySanitizer' => array(
 *						'enable' => true,
*					)
 *				)
 *			)
 *		)
 *	);
 */
class elFinderPluginMySanitizer extends elFinderPluginSanitizer
{
	protected function sanitizeFileName($filename, $opts, $allows = array()) {
		$fileName = md5(microtime());
		$fileExt  = pathinfo($name, PATHINFO_EXTENSION);
		return $fileName.'.'.$fileExt;
	}
}
```

Thanks!

**Comment by huynhquocbao92** [comment]
@nao-pon :
Sorry but Where I can create override class 

> class elFinderPluginMySanitizer extends elFinderPluginSanitizer

In **vendor\studio-42\elfinder\php\plugins\MySanitizer\plugin** ?
Thanks you.

**Comment by nao-pon** [comment]
Yes, Please try `vendor\studio-42\elfinder\php\plugins\MySanitizer\plugin.php`.

**Comment by huynhquocbao92** [comment]
@nao-pon : 
I resolved my problem. Thanks you very much 👍 👍

**Pull request closed without merging**
